version: '3.8'
services:
  backend:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      PORT: 8000
      HOST: 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - ..:/backend